### PR TITLE
removed the rewriting

### PR DESCRIPTION
**Pull request by habdelra**
Howdy Stanley!

I removed the rewriting from the plugin. You can actually accomplish this from the `ember-cli-build.js` as documented here: http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/fingerprinting/

For reference, I have my ember-cli-build.js configured like this:

``` js
/*jshint node:true*/
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
  var env = EmberApp.env() || 'development';

  var isProductionLikeBuild = ['production', 'staging'].indexOf(env) > -1;

  var fingerprintOptions = {
    enabled: true,
    extensions: ['js', 'css', 'png', 'jpg', 'gif', 'png']
  };

  switch (env) {
    case 'development':
      fingerprintOptions.prepend = 'http://localhost:4200/';
    break;
    case 'staging':
      fingerprintOptions.prepend = 'https://s3.amazonaws.com/staging-monegraph-apps-assets/';
    break;
    case 'production':
      fingerprintOptions.prepend = 'TODO';
    break;
                                                              }


module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // Add options here
    fingerprint: fingerprintOptions,
    emberCLIDeploy: {
      //runOnPostBuild: (env === 'development') ? 'devindex' : false,
      shouldActivate: true
    },
    emberCliFontAwesome: {
      useScss: true
    }
  });

  // Use `app.import` to add additional libraries to the generated
  // output files.
  //
  // If you need to use different assets in different
  // environments, specify an object as the first parameter. That
  // object's keys should be the environment name and the values
  // should be the asset to use in that environment.
  //
  // If the library that you are including contains AMD or ES6
  // modules that you would like to import into your application
  // please specify an object with the list of modules as keys
  // along with the exports of each module as its value.

  return app.toTree();
};

```

the the following is generated from the `build` step:
screen shot 2016-02-24 at 11 00 34 pm

### CODE REVIEW

**Comment by fivetanley** [comment]
This looks great! I originally stole this from @tomdale's https://github.com/tomdale/ember-cli-deploy-elastic-beanstalk/ plugin. Is this what you were trying to accomplish originally, but had to write your own code for, @tomdale?

**Comment by fivetanley** [comment]
@habdelra Can you also remove `didBuild` from the implemented hooks on the README?

**Comment by habdelra** [comment]
Will do :+1:

**Comment by habdelra** [comment]
Actually it looks like `didBuild` is not currently mentioned in the implemented hooks on the README.

screen shot 2016-02-25 at 12 27 11 pm

**Comment by fivetanley** [comment]
I deployed this to Ember API Docs staging environment (the only project using this addon at the moment that I know of!) and my smoke test seems to indicate it works! I'm going to merge this and release a 1.0.0. :tada: Thank you!

**Comment by tomdale** [comment]
Good guy @fivetanley, doesn't wait for years and hundreds of production users to cut 1.0.0.

**Pull request merged**
